import re
from playwright.sync_api import Page, expect
import os
import dotenv
dotenv.load_dotenv()

username = os.getenv("username")
password = os.getenv("password")
url = os.getenv("url")

def test_example(page: Page) -> None:
    page.goto(url)
    page.get_by_role("textbox", name="torontomu username").click()
    page.get_by_role("textbox", name="torontomu username").fill(username)
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill(password)
    page.get_by_role("button", name="Log in").click()
    page.get_by_role("textbox", name="Verification Code:").click()
    page.get_by_role("textbox", name="Verification Code:").fill("")
    page.get_by_role("button", name="Log in").click()
    page.get_by_role("link", name="Coop").click()
    page.get_by_role("link", name="Documents").first.click()
    page.locator("a").filter(has_text="Upload Document").click()
    page.get_by_role("textbox", name="Name").click()
    page.get_by_role("textbox", name="Name").fill("resume_test")
    page.get_by_label("Type").select_option("2")
    page.locator("body").select_option("2")
    page.get_by_label("Type").click()
    page.get_by_text("Upload a Document Back to Home Name Type -- Select -- Cover Letter - .pdf").click()
    page.get_by_text("Choose File").click()
    page.locator("body").set_input_files("Gajanan_Vig_Resume_AI.pdf")
    page.get_by_role("link", name="Upload Document").click()
    page.get_by_role("link", name="Upload Document").click()
    page.locator("a").filter(has_text="Upload Document").click()
    page.get_by_role("textbox", name="Name").click()
    page.get_by_role("textbox", name="Name").fill("cover letter_test")
    page.get_by_label("Type").select_option("1")
    page.locator("body").select_option("1")
    page.get_by_label("Type").click()
    page.get_by_text("Upload a Document Back to Home Name Type -- Select -- Cover Letter - .pdf").click()
    page.get_by_text("Choose File").click()
    page.locator("body").set_input_files("Gajanan_Vig_CL_AI.pdf")
    page.get_by_role("link", name="Upload Document").click()
    page.get_by_role("link", name="Upload Document").click()
    # page.get_by_role("link", name="Job Postings").first.click()
    # page.get_by_role("link", name="Shortlist").click()
    # with page.expect_popup() as page1_info:
    #     page.get_by_role("button", name="AI Transformation Engineer").click()
    # page1 = page1_info.value
    # page1.locator("#button_4694163640854586").click()
    # page1.get_by_role("radio", name="CREATE A CUSTOMIZED").check()
    # page1.get_by_role("textbox", name="Package Name * :").click()
    # page1.get_by_role("textbox", name="Package Name * :").fill("JobId_test")
    # page1.get_by_label("Cover Letter * :").select_option("2384461")
    # page1.get_by_label("Cover Letter * :").select_option("2384461")
    # page1.get_by_label("Resume * :").select_option("2384461")
    # page1.get_by_label("Resume * :").select_option("2384460")
    # page1.get_by_label("Transcript * :").select_option("2384460")
    # page1.get_by_label("Transcript * :").select_option("2286269")
    # page1.get_by_role("button", name="Submit Application").click()
